######################################################################
# Automatically generated by qmake (3.0) ? 10 31 11:05:34 2013
######################################################################

TEMPLATE = app
TARGET = cllaun
INCLUDEPATH += . src
QT += core gui widgets

# Input
HEADERS += src/main_window.h cllaun_core/src/common.h
SOURCES += src/main.cc src/main_window.cc
LIBS += F:/Projects/qt/cllaun/cllaun_core/release/cllaun.lib
